import os
import time
import uuid
import shutil
import logging
from pathlib import Path
from contextlib import asynccontextmanager
from fastapi import FastAPI, UploadFile, File, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

from app.config import settings
from app.core.security import RateLimitMiddleware, validate_file_metadata
from app.database import (
    init_db,
    insert_document,
    get_all_documents,
    delete_document,
    insert_query,
    insert_claim
)
from app.core.ingestion import DocumentIngestor, RecursiveMetadataChunker
from app.core.indexing import ChromaManager
from app.core.retrieval import HybridSearchEngine
from app.core.generation import AnswerGenerator, is_llm_available
from app.core.verification import CitationVerifier

# Uptime tracker
START_TIME = time.time()

# Setup logging
logger = logging.getLogger("rag_system.api")

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize SQLite database
    logger.info("Initializing metadata database...")
    try:
        init_db()
        logger.info("Metadata database initialized successfully.")
    except Exception as e:
        logger.critical(f"Database initialization failed: {e}")
        raise
    yield

app = FastAPI(
    title="🛡️ Verifiable RAG API",
    description="Production-grade API endpoints for multi-format document RAG with claim-level citation auditing.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan
)

# Enforce CORS configuration from Settings
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.allowed_origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Enforce in-memory IP Rate Limiting middleware
app.add_middleware(
    RateLimitMiddleware,
    limit=settings.RATE_LIMIT_PER_MINUTE
)

# Define schemas for OpenAPI documentation
class QueryRequest(BaseModel):
    query: str = Field(
        ..., 
        description="Natural language question to ask the knowledge base.",
        json_schema_extra={"example": "What are the core architecture changes in transformers?"}
    )

class DocumentLibraryResponse(BaseModel):
    id: str = Field(..., description="Unique UUID generated for the document.")
    filename: str = Field(..., description="Filename of the uploaded document.")
    filepath: str = Field(..., description="Absolute path to file on backend.")
    file_type: str = Field(..., description="File suffix/extension.")
    file_size: int = Field(..., description="File size in bytes.")
    chunk_count: int = Field(..., description="Total semantic chunks generated.")
    created_at: str = Field(..., description="Timestamp of document ingestion.")

class CitationDetail(BaseModel):
    doc_name: str = Field(..., description="Source document filename.")
    page: int = Field(..., description="Page number of cited text chunk.")
    section: str = Field(..., description="Section heading containing cited text.")
    source_idx: int = Field(..., description="Index ID of the chunk in context.")
    similarity_score: float = Field(..., description="Embedding-based cosine similarity.")
    nli_status: str = Field(..., description="Logical NLI status (SUPPORTED/CONTRADICTED/UNSUPPORTED).")
    confidence_score: float = Field(..., description="Weighted confidence score (0-100%).")

class ClaimVerificationResult(BaseModel):
    claim: str = Field(..., description="Cleaned sentence/claim extracted from answer.")
    status: str = Field(..., description="Grounding status (SUPPORTED/UNSUPPORTED/CONTRADICTED).")
    confidence_score: float = Field(..., description="Overall confidence level (0-100%).")
    similarity_score: float = Field(..., description="Best match cosine similarity score.")
    best_citation: Optional[CitationDetail] = Field(None, description="Detailed metrics of the best supporting citation.")
    citation_details: List[CitationDetail] = Field(default=[], description="Full list of all citations attached to the claim.")

class ChunkDetail(BaseModel):
    text: str = Field(..., description="Text segment content.")
    metadata: Dict[str, Any] = Field(..., description="Extracted metadata (page, section, source).")
    id: str = Field(..., description="Vector collection ID of the chunk.")
    rrf_score: Optional[float] = Field(None, description="Reciprocal Rank Fusion score.")
    rerank_score: Optional[float] = Field(None, description="Cross-Encoder reranking score.")

class QueryResponse(BaseModel):
    query_id: str = Field(..., description="Unique UUID log identifier.")
    answer: str = Field(..., description="Context-grounded answer generated by LLM.")
    is_mock: bool = Field(..., description="Flags if generation fallback to Mock Mode due to offline provider.")
    chunks: List[ChunkDetail] = Field(..., description="List of top context chunks retrieved.")
    verification_results: List[ClaimVerificationResult] = Field(..., description="Claim-by-claim grounding audit reports.")

class SystemHealthResponse(BaseModel):
    status: str = Field(..., description="Health status of API service.")
    llm_available: bool = Field(..., description="Status of configured LLM provider.")
    uptime_seconds: float = Field(..., description="System uptime.")
    metrics: Dict[str, Any] = Field(..., description="Dynamic document and storage metrics.")

# Lazy-loaded singletons to prevent high startup RAM and OOM on Render
_chroma_manager = None
_search_engine = None
_generator = None
_verifier = None

def get_chroma_manager() -> ChromaManager:
    global _chroma_manager
    if _chroma_manager is None:
        logger.info("Lazy-initializing ChromaManager...")
        _chroma_manager = ChromaManager()
    return _chroma_manager

def get_search_engine() -> HybridSearchEngine:
    global _search_engine
    if _search_engine is None:
        logger.info("Lazy-initializing HybridSearchEngine...")
        _search_engine = HybridSearchEngine(get_chroma_manager())
    return _search_engine

def get_generator() -> AnswerGenerator:
    global _generator
    if _generator is None:
        logger.info("Lazy-initializing AnswerGenerator...")
        _generator = AnswerGenerator()
    return _generator

def get_verifier() -> CitationVerifier:
    global _verifier
    if _verifier is None:
        logger.info("Lazy-initializing CitationVerifier...")
        _verifier = CitationVerifier()
    return _verifier

@app.post(
    "/upload", 
    response_model=Dict[str, Any], 
    status_code=status.HTTP_200_OK,
    tags=["Ingestion"],
    summary="Upload and index a document",
    description="Extracts content, page numbers, and headers, generates vector embeddings, and registers the file in SQLite."
)
async def upload_document(file: UploadFile = File(...)):
    filename = file.filename
    if not filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, 
            detail="Filename cannot be empty"
        )
        
    # Get file size safely
    try:
        # Seek to end to get size
        file.file.seek(0, os.SEEK_END)
        file_size = file.file.tell()
        file.file.seek(0)  # Reset to beginning
    except Exception as e:
        logger.error(f"Failed to calculate upload file size: {e}")
        file_size = 0

    # Enforce file validators (MIME/Extension and Max size limit)
    validate_file_metadata(filename, file_size)

    filepath = settings.UPLOAD_DIR / filename
    
    # Save file locally
    try:
        with filepath.open("wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        logger.info(f"Saved uploaded file: {filename} ({file_size} bytes)")
    except Exception as e:
        logger.error(f"Failed to write file {filename} to disk: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to save file: {str(e)}"
        )
        
    file_type = filepath.suffix.lower()
    doc_id = str(uuid.uuid4())
    
    # Ingestion Pipeline
    try:
        start_time = time.time()
        documents = DocumentIngestor.load_document(filepath)
        if not documents:
            filepath.unlink()
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="No readable text could be extracted from document."
            )
            
        chunker = RecursiveMetadataChunker()
        chunks = chunker.chunk_documents(documents)
        
        # ChromaDB indexing
        get_chroma_manager().add_chunks(doc_id, chunks)
        
        # SQLite Registration
        insert_document(
            doc_id=doc_id,
            filename=filename,
            filepath=str(filepath),
            file_type=file_type,
            file_size=file_size,
            chunk_count=len(chunks)
        )
        
        ingest_latency = time.time() - start_time
        logger.info(f"Document {filename} ingested in {ingest_latency:.4f}s. Total chunks: {len(chunks)}")
        
        return {
            "status": "success",
            "doc_id": doc_id,
            "filename": filename,
            "chunk_count": len(chunks)
        }
    except HTTPException:
        # Pass HTTPExceptions directly
        raise
    except Exception as e:
        if filepath.exists():
            filepath.unlink()
        logger.error(f"Error executing ingestion for {filename}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"In-depth document processing failed: {str(e)}"
        )

@app.post(
    "/query", 
    response_model=QueryResponse,
    status_code=status.HTTP_200_OK,
    tags=["Query Engine"],
    summary="Query the RAG pipeline",
    description="Retrieves document chunks using hybrid search, reranks them, generates answers, and audits citations."
)
async def query_system(payload: QueryRequest):
    query_text = payload.query.strip()
    if not query_text:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, 
            detail="Query text cannot be empty"
        )
        
    logger.info(f"Processing API query request: '{query_text}'")
    query_start = time.time()

    # 1. Retrieval
    try:
        reranked_chunks = get_search_engine().retrieve_and_rerank(query_text)
    except Exception as e:
        logger.error(f"Retrieval engine execution failure: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Hybrid search or reranking failed: {str(e)}"
        )
        
    if not reranked_chunks:
        # Returns empty structure if no docs are loaded
        return {
            "query_id": str(uuid.uuid4()),
            "answer": "No documents have been uploaded or no relevant content was found to answer this question.",
            "is_mock": False,
            "chunks": [],
            "verification_results": []
        }
        
    # 2. Answer Generation
    try:
        answer, is_mock = get_generator().generate_answer(query_text, reranked_chunks)
    except Exception as e:
        logger.error(f"Generation engine execution failure: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LLM answer generation failed: {str(e)}"
        )
        
    # 3. Citation Parsing
    parsed_claims = get_generator().parse_citations(answer, reranked_chunks)
    
    # 4. Citation Verification
    try:
        verification_results = get_verifier().verify_answer(parsed_claims)
    except Exception as e:
        logger.error(f"Verification engine execution failure: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Claim grounding verification failed: {str(e)}"
        )
        
    # 5. Database Logging
    query_id = str(uuid.uuid4())
    try:
        insert_query(query_id, query_text, answer)
        for result in verification_results:
            claim_id = str(uuid.uuid4())
            best_citation = result.get("best_citation")
            
            doc_name = best_citation["doc_name"] if best_citation else None
            page = best_citation["page"] if best_citation else None
            section = best_citation["section"] if best_citation else None
            cited_passage = None
            
            if best_citation:
                source_idx = best_citation["source_idx"] - 1
                if 0 <= source_idx < len(reranked_chunks):
                    cited_passage = reranked_chunks[source_idx]["text"]
                    
            insert_claim(
                claim_id=claim_id,
                query_id=query_id,
                claim_text=result["claim"],
                cited_passage=cited_passage,
                doc_name=doc_name,
                page_number=page,
                section_header=section,
                similarity_score=result["similarity_score"],
                nli_status=best_citation["nli_status"] if best_citation else "UNSUPPORTED",
                confidence_score=result["confidence_score"],
                is_supported=(result["status"] == "SUPPORTED")
            )
    except Exception as e:
        logger.warning(f"Failed to log query/claims details to SQLite database: {e}")

    total_latency = time.time() - query_start
    logger.info(f"API query request processed successfully in {total_latency:.4f}s")
    
    return {
        "query_id": query_id,
        "answer": answer,
        "is_mock": is_mock,
        "chunks": reranked_chunks,
        "verification_results": verification_results
    }

@app.get(
    "/documents", 
    response_model=List[DocumentLibraryResponse],
    status_code=status.HTTP_200_OK,
    tags=["Ingestion"],
    summary="List all indexed documents",
    description="Queries metadata catalog database and returns details of all ingested files."
)
async def list_documents():
    return get_all_documents()

@app.delete(
    "/documents/{doc_id}",
    response_model=Dict[str, Any],
    status_code=status.HTTP_200_OK,
    tags=["Ingestion"],
    summary="Delete an indexed document",
    description="Purges document metadata from SQLite, chunks from ChromaDB, and raw files from uploads disk."
)
async def remove_document(doc_id: str):
    docs = get_all_documents()
    target_doc = None
    for doc in docs:
        if doc["id"] == doc_id:
            target_doc = doc
            break
            
    if not target_doc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Document not found."
        )
        
    # Delete from ChromaDB
    try:
        get_chroma_manager().delete_document_chunks(doc_id)
    except Exception as e:
        logger.error(f"Failed to purge ChromaDB vectors for doc ID {doc_id}: {e}")
        
    # Delete raw file
    filepath = Path(target_doc["filepath"])
    if filepath.exists():
        try:
            filepath.unlink()
            logger.info(f"Purged uploaded file from disk: {filepath.name}")
        except Exception as e:
            logger.error(f"Failed to delete upload file {filepath}: {e}")
            
    # Delete from SQLite
    try:
        delete_document(doc_id)
    except Exception as e:
        logger.error(f"Failed to remove SQLite document metadata for doc ID {doc_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to complete document deletion from metadata database."
        )
        
    return {
        "status": "success", 
        "detail": f"Document {target_doc['filename']} has been permanently deleted."
    }

@app.get(
    "/health", 
    response_model=SystemHealthResponse,
    status_code=status.HTTP_200_OK,
    tags=["Monitoring"],
    summary="Get API health status",
    description="Returns detailed performance stats, active file counts, and provider availability."
)
async def health_check():
    llm_ok = is_llm_available()
    docs = get_all_documents()
    
    total_docs = len(docs)
    total_chunks = sum(doc.get("chunk_count", 0) for doc in docs)
    
    # Calculate sizes
    sqlite_size = 0
    if settings.SQLITE_DB_PATH.exists():
        sqlite_size = settings.SQLITE_DB_PATH.stat().st_size
        
    chroma_count = 0
    try:
        chroma_count = get_chroma_manager().collection.count()
    except Exception:
        pass
        
    return {
        "status": "healthy",
        "llm_available": llm_ok,
        "uptime_seconds": time.time() - START_TIME,
        "metrics": {
            "document_count": total_docs,
            "chunk_count": total_chunks,
            "chroma_vector_count": chroma_count,
            "sqlite_db_size_bytes": sqlite_size,
            "settings": {
                "llm_provider": settings.LLM_PROVIDER.upper(),
                "llm_model": settings.LLM_MODEL,
                "rate_limit_limit": settings.RATE_LIMIT_PER_MINUTE
            }
        }
    }
